# Generated by Django 2.0 on 2020-04-27 04:08

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_nm', models.CharField(max_length=50, unique=True)),
                ('city_pynm', models.CharField(max_length=50, unique=True)),
                ('city_statas', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility_name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Favourite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fav_city', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_name', models.CharField(max_length=191)),
                ('host_id', models.IntegerField()),
                ('host_replayRate', models.IntegerField(default=0)),
                ('host_commentNum', models.IntegerField(default=0)),
                ('host_RoomNum', models.IntegerField(default=0)),
                ('host_updateDate', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_img', models.CharField(default='static/media/default.jpg', max_length=191)),
                ('house_id', models.IntegerField(default=0)),
                ('house_cityName', models.CharField(default='未知城市', max_length=50)),
                ('house_title', models.CharField(max_length=191)),
                ('house_url', models.CharField(max_length=191)),
                ('house_date', models.DateField(default=django.utils.timezone.now)),
                ('house_firstOnSale', models.DateTimeField(default=datetime.datetime(1970, 1, 1, 1, 1, 1, 499454))),
                ('house_favcount', models.IntegerField(default=0)),
                ('house_commentNum', models.IntegerField(default=0)),
                ('house_descScore', models.FloatField(default=0)),
                ('house_talkScore', models.FloatField(default=0)),
                ('house_hygieneScore', models.FloatField(default=0)),
                ('house_positionScore', models.FloatField(default=0)),
                ('house_avarageScore', models.FloatField(default=0)),
                ('house_type', models.CharField(default='未分类', max_length=50)),
                ('house_area', models.IntegerField(default=0)),
                ('house_kitchen', models.IntegerField(default=0)),
                ('house_living_room', models.IntegerField(default=0)),
                ('house_toilet', models.IntegerField(default=0)),
                ('house_bedroom', models.IntegerField(default=0)),
                ('house_capacity', models.IntegerField()),
                ('house_bed', models.IntegerField(default=1)),
                ('house_oriprice', models.DecimalField(decimal_places=2, max_digits=16)),
                ('house_discountprice', models.DecimalField(decimal_places=2, default=0.0, max_digits=16)),
                ('house_location_text', models.CharField(max_length=191)),
                ('house_location_lat', models.DecimalField(decimal_places=6, max_digits=16)),
                ('house_location_lng', models.DecimalField(decimal_places=6, max_digits=16)),
                ('earliestCheckinTime', models.TimeField(default='00:00')),
                ('house_facility', models.ManyToManyField(to='hotelapp.Facility')),
                ('house_host', models.ManyToManyField(to='hotelapp.Host')),
            ],
        ),
        migrations.CreateModel(
            name='Labels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label_type', models.IntegerField(choices=[(0, '普通标签'), (1, '优惠标签')])),
                ('label_name', models.CharField(max_length=191, unique=True)),
                ('label_desc', models.CharField(max_length=191, unique=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='labels',
            unique_together={('label_name', 'label_desc')},
        ),
        migrations.AddField(
            model_name='house',
            name='house_labels',
            field=models.ManyToManyField(to='hotelapp.Labels'),
        ),
        migrations.AlterUniqueTogether(
            name='host',
            unique_together={('host_id', 'host_updateDate')},
        ),
        migrations.AddField(
            model_name='favourite',
            name='fav_houses',
            field=models.ManyToManyField(to='hotelapp.House'),
        ),
        migrations.AddField(
            model_name='favourite',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='house',
            unique_together={('house_id', 'house_date')},
        ),
    ]
