# Generated by Django 2.0 on 2020-04-28 00:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotelapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favourite',
            name='fav_city',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hotelapp.City'),
        ),
    ]
