# Generated by Django 2.0 on 2020-05-01 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotelapp', '0002_auto_20200428_0810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favourite',
            name='fav_city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotelapp.City'),
        ),
    ]
